name: Humiliation
main: mn.aPunch.Humiliation.Humiliation
version: 0.2.2
commands:
  hh:
    description: The Humiliation Help menu.
    usage: |
           Incorrect usage of /hh. Examples:
           /<command> 
  slap:
    description: Slap a player to deal damage.
    usage: |
           Incorrect usage of /slap. Examples:
           /<command> [player] [noun]
  humiliate:
    description: Change a player's display name.
    usage: |
           Incorrect usage of /humiliate. Examples:
           /<command> [player] [nickname]
  leash:
    description: Attach a player to you.
    usage: |
           Incorrect usage of /leash. Examples:
           /<command> [player]
